version: '3'

services:

  lottodb:
    build: ./docker/mariadb/.
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lotto
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

  lottoweb:
    image: ddle/lottoweb:latest
    container_name: web
    ports:
      - 8080:8080
    depends_on:
      - lottodb

  lottonginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/:/etc/nginx/
    depends_on:
      - lottoweb

networks:
  default:
    external:
      name: docker_net

