version: '3'

services:

  lottodb:
    build: ./docker/mariadb/.
    container_name: containerdb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lotto
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

      
  lottoweb:
    image: ddle/lottoweb:0.0.3
    container_name: containerweb
    ports:
      - 8080:8080
    depends_on:
      - lottodb
  
  lottonginx:
    image: nginx
    container_name: containernginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx_conf:/etc/nginx/nginx.conf
    depends_on:
      - lottoweb

  lottoserver:
    image: ddle/lottopush:server0.0.2
    container_name: pushserver
    depends_on:
      - lottodb
    ports:
      - 3002:3002

    
  lottoreact:
    image: ddle/lottopush:front0.0.1
    container_name: pushfront
    depends_on:
      - lottoserver
    ports:
      - 3000:3000
